# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPapers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=200)),
                ('institutions', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
