# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('state', models.IntegerField(default=2)),
                ('tag', models.TextField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='MySideBar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_name', models.CharField(max_length=200)),
                ('entry_content', models.TextField()),
                ('sub_entry_name', models.TextField()),
                ('sub_entry_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_level', models.CharField(max_length=200)),
                ('second_level', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mypapers',
            name='state',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='mypapers',
            name='tag',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mypapers',
            name='time',
            field=models.CharField(default='0000-00-00', max_length=100),
        ),
    ]
