# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160921_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
